name = "icra-contractors-v1"
main = "src/worker.js"
compatibility_date = "2026-06-01"
workers_dev = false

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "force-trailing-slash"

[vars]
SITE_URL = "https://icra.contractors/"
